# Generated by Django 3.1.5 on 2021-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.CharField(max_length=20)),
                ('open_prc', models.IntegerField()),
                ('high_prc', models.IntegerField()),
                ('low_prc', models.IntegerField()),
                ('close_prc', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('cum_volume', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
