# Generated by Django 3.1.6 on 2021-02-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='account_num_fut',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='account_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
